# Generated by Django 2.1.15 on 2022-08-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_photobox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobox',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=16),
        ),
        migrations.AlterField(
            model_name='photobox',
            name='lon',
            field=models.DecimalField(decimal_places=14, max_digits=17),
        ),
    ]
