# Generated by Django 2.1.15 on 2022-08-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0004_auto_20220813_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photobox',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
    ]
